apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: default
  labels:
    app: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    command: [ "sleep", "3600" ]   # keeps the pod running for testing
  restartPolicy: Always
