apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"sampapp","namespace":"argocd"},"spec":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"manifests","repoURL":"https://github.com/mikiangelica/k8s-manifests.git","targetRevision":"master"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}
    creationTimestamp: "2025-09-24T12:40:57Z"
    generation: 68
    name: sampapp
    namespace: argocd
    resourceVersion: "106459"
    uid: e94435c4-0ff3-4e18-bcc4-4043dad90603
  spec:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: manifests
      repoURL: https://github.com/mikiangelica/k8s-manifests.git
      targetRevision: master
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2025-09-24T12:41:19Z"
      status: Healthy
    reconciledAt: "2025-09-25T07:55:14Z"
    resourceHealthSource: appTree
    sourceType: Directory
    sync:
      comparedTo:
        destination:
          namespace: default
          server: https://kubernetes.default.svc
        source:
          path: manifests
          repoURL: https://github.com/mikiangelica/k8s-manifests.git
          targetRevision: master
      revision: b5f569de4692b257064b5244e07b558e1a5cdeeb
      status: Synced
kind: List
metadata:
  resourceVersion: ""
